name: deploy

# 代码提交到main分支时触发github action
on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: BLOG_TOKEN
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v3
          with:
              hugo-version: "latest"
              extended: true

        - name: Build Web
          run: hugo -D

        - name: Deploy Web
          uses: peaceiris/actions-gh-pages@v4
          with:
              PERSONAL_TOKEN: ${{ secrets.BLOG_TOKEN }}
              EXTERNAL_REPOSITORY: zhangzib123/zhangzib123.github.io
              PUBLISH_BRANCH: publish
              PUBLISH_DIR: ./public
              commit_message: auto deploy
# test  444 55